### ISSUE TITLE
struct.error: unpack requires a buffer of 267 bytes

### ISSUE THREAD

**Issue by ryny24** [AsmSafone/MusicPlayer#34]
I've gone through the legacy setup on 2 different machines, I get this same error. Anyone know what it means? The last machine has 24 GB of ram.

`ryan@cpw-eth380:~/MusicPlayer$ python3 main.py
WARNING: SPOTIFY_CLIENT_ID or SPOTIFY_CLIENT_SECRET is not set.Bot will work fine but playing songs with spotify playlist won't work.Check your configs or .env file if you want to add them or ask @AsmSupport!
Traceback (most recent call last):
  File "main.py", line 671, in <module>
    pytgcalls.run()
  File "/home/ryan/.local/lib/python3.8/site-packages/pytgcalls/sync.py", line 34, in async_to_sync_wrap
    return loop.run_until_complete(coroutine)
  File "/usr/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/home/ryan/.local/lib/python3.8/site-packages/pytgcalls/methods/utilities/run.py", line 31, in run
    await self.start()
  File "/home/ryan/.local/lib/python3.8/site-packages/pytgcalls/methods/utilities/start.py", line 36, in start
    await self._init_mtproto()
  File "/home/ryan/.local/lib/python3.8/site-packages/pytgcalls/methods/utilities/mtproto_handler.py", line 12, in _init_mtproto
    await self._app.start()
  File "/home/ryan/.local/lib/python3.8/site-packages/pytgcalls/mtproto/mtproto_client.py", line 149, in start
    await self._bind_client.start()
  File "/home/ryan/.local/lib/python3.8/site-packages/pytgcalls/mtproto/pyrogram_client.py", line 406, in start
    await self._app.start()
  File "/home/ryan/.local/lib/python3.8/site-packages/pyrogram/methods/utilities/start.py", line 52, in start
    is_authorized = await self.connect()
  File "/home/ryan/.local/lib/python3.8/site-packages/pyrogram/methods/auth/connect.py", line 39, in connect
    await self.load_session()
  File "/home/ryan/.local/lib/python3.8/site-packages/pyrogram/client.py", line 674, in load_session
    await self.storage.open()
  File "/home/ryan/.local/lib/python3.8/site-packages/pyrogram/storage/memory_storage.py", line 38, in open
    dc_id, test_mode, auth_key, user_id, is_bot = struct.unpack(
struct.error: unpack requires a buffer of 267 bytes
ryan@cpw-eth380:~/MusicPlayer$
`

**Comment by ryny24** [comment]
Was able to fix by generating SESSION from "python3 genStr.py" instead of an online resource. Thank you!
